version: '3.1'

volumes:
  scoringenginedb:
    driver: local

services:

  api_integration_orchestrator:
    build:
        context: .
        dockerfile: docker/api/Dockerfile
    container_name: api_integration_orchestrator
    env_file:
      - "docker/api/.envvars"
    ports:
      - "80:${PORT:-80}"
    volumes:
      - ".:/app"


